version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: study_event_api_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: