// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Event struct {
	ID   int32     `json:"id"`
	Name string    `json:"name"`
	Date time.Time `json:"date"`
}
