// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEvent(ctx context.Context, id int32) error
	GetEvent(ctx context.Context, id int32) (Event, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
